name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Deploy To Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    script: 
                        cd /var/www/html/${{ secrets.DEPLOYHOST }}/ && 
                        git pull && 
                        composer update &&
                        php artisan test &&
                        php artisan env:set NS_MODULES_MANAGEMENT_DISABLED --v=false &&
                        php artisan config:clear &&
                        php artisan modules:enable Demo &&
                        php artisan env:set NS_MODULES_MANAGEMENT_DISABLED --v=true &&
                        php artisan config:clear &&
                        npm run prod
