name: Build and Deploy 
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Deploy To Server
                uses: appleboy/ssh-action@master
                continue-on-error: true
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: 
                        cd /var/www/html/${{ secrets.DEPLOYHOST }}/ && git pull && composer update;
            -   name: Deploy To Grants
                uses: appleboy/ssh-action@master
                continue-on-error: true
                with:
                    host: ${{ secrets.GRANTSHOST }}
                    username: ${{ secrets.GRANTSUSER }}
                    password: ${{ secrets.GRANTPASSWORD }}
                    port: ${{ secrets.GRANTSPORT }}
                    script: 
                        cd /var/www/html/${{ secrets.GRANTSPATH }}/ && git pull && composer update && cd modules/NsMultiStore && git pull;
            -   name: Deploy To AHD
                uses: appleboy/ssh-action@master
                continue-on-error: true
                with:
                    host: ${{ secrets.GRANTSHOST }}
                    username: ${{ secrets.GRANTSUSER }}
                    password: ${{ secrets.GRANTPASSWORD }}
                    port: ${{ secrets.GRANTSPORT }}
                    script:
                        cd /var/www/html/${{ secrets.AHDPATH }}/ && git pull && composer update && cd modules/NsMultiStore && git pull;
