name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Connecting Deploy Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: 
                        cd /var/www/html/deploy-v4.nexopos.com/; 
                        git clone https://github.com/blair2004/NexoPOS-4x .;
                        composer install;
                        cp .env.example .env;
                        php artisan generate:key;
                        npm i;
                        npm run prod;                   
