name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Deploy To Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: 
                        mv /var/www/html/${{ secrets.DEPLOYHOST }}/.env /var/www/html/backup.env;
                        rm -rf /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        mkdir /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        mv /var/www/html/backup.env /var/www/html/${{ secrets.DEPLOYHOST }}/.env;
                        rm /var/www/html/backup.env;
                        cd /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        git clone https://github.com/blair2004/NexoPOS-4x .;
                        composer install;
                        /usr/bin/php artisan key:generate;
                        npm i;
                        npm run prod;                   
                        chown php-fpm /var/www/html/${{ secrets.DEPLOYHOST }} -R;
