name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Deploy To Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: 
                        cd /var/www/html/${{ secrets.DEPLOYHOST }}/ && git pull && composer update; php artisan test; /root/.nvm/versions/node/v15.3.0/bin/npm run prod;
