name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:               
            -   name: Connecting Deploy Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    script: 
                        rm -rf /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        mkdir /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        cd /var/www/html/${{ secrets.DEPLOYHOST }}/; 
                        git clone https://github.com/blair2004/NexoPOS-4x .;
                        composer install;
                        cp .env.example .env;
                        chown php-fpm . -R;
                        /usr/bin/php artisan generate:key;
                        npm i;
                        npm run prod;                   
